version: 2
jobs:
  build:
    working_directory: ~/code
  
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      -sudo ANDROID_HOME: /Users/mac/Library/Developer/Xamarin/android-sdk-macosx ./gradlew dependencies
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      -  test:
         override:
        # start the build
        - ./gradlew assembleDebug
        # copy the build outputs to artifacts
       - cp -r app/build/outputs/ $CIRCLE_ARTIFACTS
